### ISSUE TITLE
Make create date and edit date different

### ISSUE THREAD

**Issue by russelldj** [open-forest-observatory/ofo-docs#7]
In the bottom toolbar, there are supposed to be both a create date and most recent edit date. However, they are currently the same.

**Comment by asidhu0** [comment]
They are the same because the plugin pulls dates from the git commit history that affects each file. Since the `Docs Home` page was created and last modified on December 16, 2023, it shows the same date. However, navigating to 
`Internal Docs` --> `Using Jetstream2 for OFO development` will show different and accurate dates per the commit history. 

With this behavior, the update date best reflects when each page was last updated. 

Another possible implementation could be to update the last edited date of a page if one of its child pages got edited. Since the main heading pages are not likely to be updated much after creation, we could have their last update date reflect the most recently updated child date. The current extension we are using does not support this and I'm not sure if other date extensions do either. But if this is a good idea, I can take a look into it. 

What do you think?

**Comment by youngdjn** [comment]
Huh! In my browser, the `Using Jetstream2 for OFO development` page shows the same create and modify date! (I checked in Firefox and Chrome.) In your browser, they are different?

![image](https://github.com/open-forest-observatory/ofo-docs/assets/22568494/2eb87ec1-bd7b-4b80-849b-02bab71002d3)

I'm ambivalent on whether we need to update the date of parent pages if a child gets updated. My inclination is no, because often we may have actual content on the parent pages, and I think we'd want it to reflect the edit date of that page.

**Comment by russelldj** [comment]
I was about to post the same thing! Using Windows and Chrome (and now Firefox as well).

**Comment by russelldj** [comment]
Notably, all the edit dates across the website are the same for me, April 24th. That is the last commit to the repository. 

I'll defer to @youngdjn here on the child pages, but my initial reaction is similar.

**Comment by asidhu0** [comment]
I agree I think the best option is to have the default behavior. 

So this is strange but the same dates show for me also when I open the website on Chrome on my Mac, but when I run `mkdocs serve` to test locally the correct dates appear across the entire site. And this is with the current code in the repository. Not sure at all why this is happening, but I'll look more into it.

**Comment by youngdjn** [comment]
One idea is that it has to do with how the site is being built and served (GitHub pages) and the versions of MkDocs and its plugins that are installed there.

**Comment by asidhu0** [comment]
Resolved with PR #8
